# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Sun Apr 26 14:58:09 PDT 2015
#
#/ usage: tools-fox:rdp  --server <> [ --user <Administrator>] [ --password <>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {

    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --server) rerun_option_check $# $1; SERVER=$2 ; shift ;;
            --user) rerun_option_check $# $1; USER=$2 ; shift ;;
            --password) rerun_option_check $# $1; PASSWORD=$2 ; shift ;;
            # help option
            -|--*?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$USER" ] && USER="$(rerun_property_get $RERUN_MODULE_DIR/options/user DEFAULT)"
    # Check required options are set
    [ -z "$SERVER" ] && { echo >&2 "missing required option: --server" ; return 2 ; }
    # If option variables are declared exportable, export them.

    #
    return 0
}


# If not already set, initialize the options variables to null.
: ${SERVER:=}
: ${USER:=}
: ${PASSWORD:=}


